# 测试项目
[project]
project = 'test_project'

# 测试报告
[report]
tester_name = '123'

# html 测试报告
[report.html]
title = "自动化测试报告"

# 数据库
[mysql]
host = '127.0.0.1'
port = 3306
user = 'root'
password = '123456'
database = 'test'

# 邮件
[email]
host_server = 'smtp.qq.com'
port = 465
user = '12345678@qq.com'
password = '12345678'
send_to = '87654321@qq.com'  # if more, use: [str]
is_ssl = true

# 请求发送
[request]
timeout = 10
verify = false
redirects = true
proxies.http = ''
proxies.https = ''
