name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  check:
    name: checks
    runs-on: ubuntu-latest
    env:
      SKIP: true
    steps:
      - name: check GITHUB_REF matches package version
        uses: samuelcolvin/check-python-version@v3.2
        with:
          version_file_path: fastpt/__init__.py
    if: ${{ env.SKIP }} == 'true'
